#!/usr/bin/env python3
"""Vendor randovania's prime2 logic/pickup databases into this world's data/,
and (re)generate options_tricks.py from the trick resource database.

This script is excluded from built .apworld archives (see ../.apignore) and
is never imported at runtime; it only needs to run in a randovania dev
checkout, not in a MultiWorldGG install.

Usage:
    python tools/sync_randovania_data.py [--randovania-root PATH]

By default ``--randovania-root`` is ``../randovania`` relative to this
world's package directory (i.e. a sibling checkout next to metroidprime2/
in the repo root).
"""

from __future__ import annotations

import argparse
import copy
import json
import re
import subprocess
from pathlib import Path
from typing import Any

WORLD_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_RANDOVANIA_ROOT = WORLD_ROOT.parent / "randovania"

EXPECTED_SCHEMA_VERSION = 34
EXPECTED_GAME = "prime2"
EXPECTED_PICKUP_NODE_COUNT = 119

LEVEL_NAMES = {1: "beginner", 2: "intermediate", 3: "advanced", 4: "expert", 5: "ludicrous"}
_TAG_RE = re.compile(r"<[^>]+>")


# --------------------------------------------------------------------------
# Generic strip helpers
# --------------------------------------------------------------------------

def _strip_requirement_comments(obj: Any) -> None:
    """Recursively null out every requirement ``data.comment``, in place."""
    if isinstance(obj, dict):
        if obj.get("type") in ("and", "or") and isinstance(obj.get("data"), dict):
            data = obj["data"]
            if "comment" in data:
                data["comment"] = None
        for value in obj.values():
            _strip_requirement_comments(value)
    elif isinstance(obj, list):
        for item in obj:
            _strip_requirement_comments(item)


def _blank_keys(obj: Any, replacements: dict[str, Any]) -> None:
    """Recursively replace the value of any dict key found in ``replacements``
    with its configured blank value (a fresh copy, since values are mutable).
    """
    if isinstance(obj, dict):
        for key, blank in replacements.items():
            if key in obj:
                obj[key] = copy.deepcopy(blank)
        for value in obj.values():
            _blank_keys(value, replacements)
    elif isinstance(obj, list):
        for item in obj:
            _blank_keys(item, replacements)


def _strip_header(header: dict) -> None:
    header["minimal_logic"] = None
    header["hint_feature_database"] = {}
    for dock_type in header["dock_type_database"]["types"].values():
        dock_type["weakness_distributor"] = None
    _strip_requirement_comments(header)


def _strip_region(doc: dict) -> None:
    for area in doc["areas"].values():
        if "hint_features" in area:
            area["hint_features"] = []
        for node in area["nodes"].values():
            if "description" in node:
                node["description"] = ""
            if "hint_features" in node:
                node["hint_features"] = []
    _strip_requirement_comments(doc)


def _strip_pickup_database(doc: dict) -> None:
    _blank_keys(doc, {"offworld_models": {}, "hint_features": []})


def _write_compact(path: Path, data: Any) -> None:
    path.write_text(json.dumps(data, separators=(",", ":")), encoding="utf-8")


def _strip_html(text: str) -> str:
    text = _TAG_RE.sub(" ", text)
    return re.sub(r" +", " ", text).strip()


# --------------------------------------------------------------------------
# options_tricks.py generation
# --------------------------------------------------------------------------

def generate_options_tricks(header: dict, out_path: Path) -> int:
    tricks: dict[str, dict] = header["resource_database"]["tricks"]
    used_trick_levels: dict[str, list[int]] = header.get("used_trick_levels", {})

    lines = [
        '"""Trick difficulty options, generated by tools/sync_randovania_data.py',
        "from resource_database.tricks in the randovania prime2 logic database.",
        "",
        "Do not edit by hand -- re-run the sync script instead.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from Options import Choice",
        "",
        "",
    ]

    names_entries: list[tuple[str, str]] = []
    classes_entries: list[tuple[str, str]] = []

    for short_name in sorted(tricks):
        trick = tricks[short_name]
        long_name = trick["long_name"]
        description = _strip_html(trick.get("description") or "")
        levels = used_trick_levels.get(short_name, [])
        level_names = ", ".join(LEVEL_NAMES[level] for level in levels) if levels else "none"

        class_name = f"Trick{short_name}"
        attr_name = f"trick_{short_name.lower()}"

        doc_body = [long_name]
        if description:
            doc_body.append("")
            doc_body.append(description)
        doc_body.append("")
        doc_body.append(f"Used difficulty levels in logic: {level_names}.")
        docstring = "\n    ".join(doc_body)

        lines.append(f"class {class_name}(Choice):")
        lines.append(f'    """{docstring}')
        lines.append('    """')
        lines.append(f'    display_name = "Trick: {long_name}"')
        lines.append("    option_use_global = 0")
        lines.append("    option_disabled = 1")
        lines.append("    option_beginner = 2")
        lines.append("    option_intermediate = 3")
        lines.append("    option_advanced = 4")
        lines.append("    option_expert = 5")
        lines.append("    option_ludicrous = 6")
        lines.append("    default = 0")
        lines.append("")
        lines.append("")

        names_entries.append((short_name, attr_name))
        classes_entries.append((short_name, class_name))

    lines.append("TRICK_OPTION_NAMES: dict[str, str] = {")
    for short_name, attr_name in names_entries:
        lines.append(f"    {short_name!r}: {attr_name!r},")
    lines.append("}")
    lines.append("")
    lines.append("TRICK_OPTION_CLASSES: dict[str, type] = {")
    for short_name, class_name in classes_entries:
        lines.append(f"    {short_name!r}: {class_name},")
    lines.append("}")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    return len(tricks)


# --------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------

def main(randovania_root: Path, out_dir: Path | None = None) -> None:
    out_dir = out_dir or (WORLD_ROOT / "data")
    logic_db_src = randovania_root / "randovania" / "games" / "prime2" / "logic_database"
    pickup_db_src = (
        randovania_root / "randovania" / "games" / "prime2" / "pickup_database" / "pickup-database.json"
    )

    header = json.loads((logic_db_src / "header.json").read_text(encoding="utf-8"))
    assert header["schema_version"] == EXPECTED_SCHEMA_VERSION, (
        f"expected schema_version {EXPECTED_SCHEMA_VERSION}, got {header['schema_version']}"
    )
    assert header["game"] == EXPECTED_GAME, f"expected game {EXPECTED_GAME!r}, got {header['game']!r}"

    region_files: list[str] = header["regions"]

    out_logic_dir = out_dir / "logic_database"
    out_logic_dir.mkdir(parents=True, exist_ok=True)

    total_nodes = 0
    total_pickups = 0
    total_events = 0
    event_names: set[str] = set()

    header_copy = copy.deepcopy(header)
    _strip_header(header_copy)
    _write_compact(out_logic_dir / "header.json", header_copy)

    for region_file in region_files:
        doc = json.loads((logic_db_src / region_file).read_text(encoding="utf-8"))
        for area in doc["areas"].values():
            for node in area["nodes"].values():
                total_nodes += 1
                node_type = node["node_type"]
                if node_type == "pickup":
                    total_pickups += 1
                elif node_type == "event":
                    total_events += 1
                    event_names.add(node["event_name"])

        region_copy = copy.deepcopy(doc)
        _strip_region(region_copy)
        _write_compact(out_logic_dir / region_file, region_copy)

    assert total_pickups == EXPECTED_PICKUP_NODE_COUNT, (
        f"expected {EXPECTED_PICKUP_NODE_COUNT} pickup nodes, got {total_pickups}"
    )

    pickup_db = json.loads(pickup_db_src.read_text(encoding="utf-8"))
    _strip_pickup_database(pickup_db)
    _write_compact(out_dir / "pickup_database.json", pickup_db)

    try:
        version = subprocess.run(
            ["git", "-C", str(randovania_root), "describe", "--tags"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError, OSError):
        version = "unknown"
    (out_dir / "RANDOVANIA_VERSION.txt").write_text(version + "\n", encoding="utf-8")

    trick_count = generate_options_tricks(header, WORLD_ROOT / "options_tricks.py")

    print(f"randovania root: {randovania_root}")
    print(f"randovania version: {version}")
    print(f"regions: {len(region_files)}")
    print(f"nodes: {total_nodes}")
    print(f"pickup nodes: {total_pickups}")
    print(f"event nodes: {total_events} ({len(event_names)} distinct event names)")
    print(f"tricks: {trick_count}")
    print(f"requirement templates: {len(header['resource_database']['requirement_template'])}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--randovania-root",
        type=Path,
        default=DEFAULT_RANDOVANIA_ROOT,
        help="Path to a randovania checkout (default: %(default)s)",
    )
    args = parser.parse_args()
    main(args.randovania_root.resolve())
