"""Regenerates ``README.md`` (the human-facing manual test book) from every
``mt*.py`` module's ``TEST`` spec, so the book can never drift from the
scripts (MANUAL_TEST_PLAN.md section 6).

Run under MultiWorldGG's interpreter::

    cd MultiWorldGG
    SKIP_REQUIREMENTS_UPDATE=1 .venv/bin/python \
        -m worlds.metroidprime2.test.manual.build_readme
"""

from __future__ import annotations

from pathlib import Path

from .catalog import TESTS
from .harness import render_instructions

README_PATH = Path(__file__).parent / "README.md"

_HEADER = """\
# Metroid Prime 2: Echoes -- manual (in-game) test book

GENERATED by `build_readme.py` from every `mt*.py` module's `TEST` spec --
do not edit by hand. Regenerate with:

```
cd MultiWorldGG
SKIP_REQUIREMENTS_UPDATE=1 .venv/bin/python -m worlds.metroidprime2.test.manual.build_readme
```

`MANUAL_TEST_PLAN.md` is the design; this is the runnable book it produces.
"""

_PREREQUISITES = """\
## Prerequisites

* A MultiWorldGG source checkout (this repo) with its venv, and this world's
  symlink in place (`MultiWorldGG/worlds/metroidprime2 -> metroidprime2`).
* A vanilla **NTSC-U** Metroid Prime 2: Echoes ISO (and ideally a **PAL** one
  for `MT13`). NKit/RVZ/WIA/GCZ/CISO images are not supported.
* Dolphin with the memory engine reachable, and `host.yaml`'s
  `metroidprime2_options.rom_file` / `emulator_settings.executable_path` set.
* `ppc-asm>=1.9.0` installed (host generation imports it via the patch
  pipeline); `SKIP_REQUIREMENTS_UPDATE=1` keeps world auto-discovery from
  pip-installing every other world's requirements.
"""

_HOWTO = """\
## How to run any test

```
1. Build      python -m worlds.metroidprime2.test.manual.<slug> --iso <vanilla.iso>
2. Host       python MultiServer.py manual_tests/<slug>/<slug>.zip
3. Connect    python Launcher.py "Metroid Prime 2 Client" manual_tests/<slug>/<slug>.apmp2 <vanilla.iso>
4. Steps      follow the section below
5. Pass if    every pass criterion below holds
6. If it fails, inspect the files named under "If it fails, look at"
```

Shared flags: `--iso PATH`, `--pal`, `--out DIR`, `--clean`, `--no-patch`,
`--verify`, `--repin`, `--print-readme`, `--variant <name>`.

`--verify` builds and checks the pinned `config.json` hash without patching;
`--repin` prints the new hash to paste into the test module when a deliberate
change moved it. `client.py` has no `__main__` guard, so it is started
through the Launcher, not `python -m`; the ISO is already patched by step 1,
so the client reuses it rather than re-patching.
"""

_RESULTS = """\
## Results table to copy

| ID | Date | ISO version | Result | Notes |
|---|---|---|---|---|
| MT01 | | NTSC / PAL | pass / fail | |
| MT02 | | | | |
| MT03 | | | | |
| MT04 | | | | |
| MT05 | | | | |
| MT06 | | | | |
| MT07 | | | | |
| MT08 | | | | |
| MT09 | | | | |
| MT10 | | | | |
| MT11 | | | | |
| MT12 | | | | |
| MT13 | | | | |
"""

_SUGGESTED = """\
## Suggested runs

* **Smoke** -- `MT01`, `MT03` (boot + goal detection).
* **Pre-release** -- every P0 and P1 test.
* **Everything** -- P0 + P1 + P2.

`MT10` may crash the game by design (unverified cross-game models); run it
last in a session and note which entry crashed.
"""


def generate_readme() -> str:
    parts: list[str] = [_HEADER, _PREREQUISITES, _HOWTO, _RESULTS]

    parts.append("## Tests\n")
    for test in TESTS:
        parts.extend(
            [render_instructions(test, base_dir="manual_tests")]
            + [
                render_instructions(test, variant=variant, base_dir="manual_tests")
                for variant in test.variants
            ]
        )

    parts.append(_SUGGESTED)
    return "\n".join(parts).rstrip() + "\n"


def main() -> None:
    text = generate_readme()
    README_PATH.write_text(text, encoding="utf-8")
    print(f"Wrote {README_PATH} ({len(TESTS)} tests)")


if __name__ == "__main__":
    main()
