"""The item-collection strip shown below the client window (mirrors
``worlds/metroidprime``'s MetroidPrimeClient panel): counters for tanks,
ammo and keys, plus a grid of every upgrade, dimmed until owned.

``compute_panel_state`` is pure (names in, display state out) so it can be
tested without kivy; ``build_panel`` is the thin kivy layer on top. Icons
live in ``assets/items`` and are generated by ``tools/make_tracker_icons.py``.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

from ..items import PROGRESSIVE_ITEMS
from .receive_items import compute_desired_capacities

if TYPE_CHECKING:
    from kivymd.uix.fitimage import FitImage

MISSILE_SLOT = 44
POWER_BOMB_SLOT = 43
DARK_AMMO_SLOT = 45
LIGHT_AMMO_SLOT = 46
MISSILE_LAUNCHER_FLAG_SLOT = 73

UNLIMITED = "∞"

# Beam ammo tops out at 50 (the beam) + 10 expansions x 20. Counters with a
# fixed maximum are clamped to it: the server can resend items (e.g. the
# collect on goal completion), and a counter must never read past its max.
BEAM_AMMO_MAX = 250
SKY_TEMPLE_KEYS_TOTAL = 9
DARK_TEMPLE_KEYS_TOTAL = 3

# (icon stem, item that lights it). Two rows of 16 in the window, so the
# first 16 are "combat" and the rest "exploration"; order within a row is
# the order in game menus.
UPGRADES: tuple[tuple[str, str], ...] = (
    ("powerbeam", "Power Beam"),
    ("darkbeam", "Dark Beam"),
    ("lightbeam", "Light Beam"),
    ("annihilatorbeam", "Annihilator Beam"),
    ("chargebeam", "Charge Beam"),
    ("supermissile", "Super Missile"),
    ("darkburst", "Darkburst"),
    ("sunburst", "Sunburst"),
    ("sonicboom", "Sonic Boom"),
    ("combatvisor", "Combat Visor"),
    ("scanvisor", "Scan Visor"),
    ("darkvisor", "Dark Visor"),
    ("echovisor", "Echo Visor"),
    ("variasuit", "Varia Suit"),
    ("darksuit", "Dark Suit"),
    ("lightsuit", "Light Suit"),
    ("morphball", "Morph Ball"),
    ("morphballbomb", "Morph Ball Bomb"),
    ("boostball", "Boost Ball"),
    ("spiderball", "Spider Ball"),
    ("powerbomb", "Power Bomb"),
    ("spacejumpboots", "Space Jump Boots"),
    ("gravityboost", "Gravity Boost"),
    ("grapplebeam", "Grapple Beam"),
    ("screwattack", "Screw Attack"),
    ("missilelauncher", "Missile Launcher"),
    ("seekerlauncher", "Seeker Launcher"),
    ("violettranslator", "Violet Translator"),
    ("ambertranslator", "Amber Translator"),
    ("emeraldtranslator", "Emerald Translator"),
    ("cobalttranslator", "Cobalt Translator"),
)

# (icon stem, counter key) in display order.
COUNTERS: tuple[tuple[str, str], ...] = (
    ("energytank", "energy_tanks"),
    ("missileexpansion", "missiles"),
    ("powerbombexpansion", "power_bombs"),
    ("darkammoexpansion", "dark_ammo"),
    ("lightammoexpansion", "light_ammo"),
    ("skytemplekey", "sky_temple_keys"),
    ("darkagonkey", "dark_agon_keys"),
    ("darktorvuskey", "dark_torvus_keys"),
    ("ingkey", "ing_hive_keys"),
)

_DARK_TEMPLE_KEY_PREFIXES = {
    "dark_agon_keys": "Dark Agon Key",
    "dark_torvus_keys": "Dark Torvus Key",
    "ing_hive_keys": "Ing Hive Key",
}


@dataclass
class PanelState:
    counters: dict[str, str] = field(default_factory=dict)
    owned: dict[str, bool] = field(default_factory=dict)
    """Keyed by icon stem."""


def _resolve_progressive(names: Iterable[str]) -> list[str]:
    """Replaces each Progressive item copy with the concrete item it
    currently represents (1st Progressive Suit -> Dark Suit, 2nd -> Light
    Suit, ...), so ownership checks below only ever see concrete names."""
    resolved: list[str] = []
    copies: dict[str, int] = {}
    for name in names:
        stages = PROGRESSIVE_ITEMS.get(name)
        if stages is None:
            resolved.append(name)
            continue
        index = copies.get(name, 0)
        copies[name] = index + 1
        resolved.append(stages[min(index, len(stages) - 1)])
    return resolved


def compute_panel_state(received_names: Iterable[str], slot_data: dict[str, Any]) -> PanelState:
    """``received_names`` is ``ctx.items_received`` mapped to item names, in
    receipt order (including the starting inventory)."""
    names = list(received_names)
    concrete = _resolve_progressive(names)
    have = set(concrete)

    # Launcher/Power Bomb unlocks and ammo totals come from the same model
    # that drives what the client actually grants, so the panel can't
    # disagree with the game.
    capacities = compute_desired_capacities(
        [(name, 0) for name in names],
        0,
        bool(slot_data.get("missile_expansions_unlock_launcher", False)),
        bool(slot_data.get("power_bomb_expansions_unlock_power_bombs", False)),
    )

    state = PanelState()
    for icon, item in UPGRADES:
        state.owned[icon] = item in have
    state.owned["missilelauncher"] = capacities.get(MISSILE_LAUNCHER_FLAG_SLOT, 0) > 0
    state.owned["powerbomb"] = capacities.get(POWER_BOMB_SLOT, 0) > 0

    unlimited_missiles = "Unlimited Missiles" in have
    unlimited_beam_ammo = "Unlimited Beam Ammo" in have
    state.counters["energy_tanks"] = str(capacities.get(42, 0))
    state.counters["missiles"] = UNLIMITED if unlimited_missiles else str(capacities.get(MISSILE_SLOT, 0))
    state.counters["power_bombs"] = str(capacities.get(POWER_BOMB_SLOT, 0))
    for counter, slot in (("dark_ammo", DARK_AMMO_SLOT), ("light_ammo", LIGHT_AMMO_SLOT)):
        state.counters[counter] = UNLIMITED if unlimited_beam_ammo else str(min(capacities.get(slot, 0), BEAM_AMMO_MAX))

    # Keys are unique items, so count distinct names: a repeated delivery of
    # the same key must not count twice.
    sky_keys = len({name for name in have if name.startswith("Sky Temple Key ")})
    required = slot_data.get("sky_temple_keys_required")
    if required:
        state.counters["sky_temple_keys"] = f"{min(sky_keys, required)}/{required}"
    else:
        state.counters["sky_temple_keys"] = str(min(sky_keys, SKY_TEMPLE_KEYS_TOTAL))
    for counter, prefix in _DARK_TEMPLE_KEY_PREFIXES.items():
        owned = len({name for name in have if name.startswith(prefix)})
        state.counters[counter] = f"{min(owned, DARK_TEMPLE_KEYS_TOTAL)}/{DARK_TEMPLE_KEYS_TOTAL}"

    return state


# --------------------------------------------------------------------------
# kivy layer
# --------------------------------------------------------------------------

ICON_SIZE_DP = 24
COUNTER_ICON_DP = 32
UPGRADE_ROWS = 2


def get_image(stem: str, size_dp: int) -> FitImage:
    from importlib import resources
    from io import BytesIO

    from kivy.core.image import Image
    from kivy.metrics import dp
    from kivymd.uix.fitimage import FitImage

    resource = resources.files(f"{__package__.rsplit('.', 1)[0]}.assets.items").joinpath(f"{stem}.png")
    texture = Image(BytesIO(resource.read_bytes()), ext="png").texture
    image = FitImage(texture=texture)
    image.size_hint = (None, None)
    image.size = (dp(size_dp), dp(size_dp))
    image.fit_mode = "scale-down"
    return image


class ItemPanel:
    """Holds the kivy widgets; ``layout`` is what gets added to the window."""

    def __init__(self) -> None:
        from kivy.metrics import dp
        from kvui import MDBoxLayout, MDGridLayout, MDLabel

        self.layout = MDBoxLayout(
            orientation="horizontal",
            size_hint_y=None,
            height=dp(64),
            spacing=dp(5),
            padding=dp(5),
        )

        self.counter_labels: dict[str, MDLabel] = {}
        for stem, key in COUNTERS:
            column = MDGridLayout(
                rows=2,
                spacing=dp(3),
                size_hint_x=None,
                width=dp(COUNTER_ICON_DP + 12),
                row_default_height=dp(COUNTER_ICON_DP),
                row_force_default=True,
            )
            icon = get_image(stem, COUNTER_ICON_DP)
            # Span the column so scale-down centers the icon over the (centered)
            # label instead of leaving it pinned to the cell's left edge.
            icon.size_hint_x = 1
            column.add_widget(icon)
            label = MDLabel(text="0", halign="center", valign="middle", role="medium")
            label.bind(size=lambda inst, val: setattr(inst, "text_size", val))
            column.add_widget(label)
            self.counter_labels[key] = label
            self.layout.add_widget(column)

        self.upgrade_icons: dict[str, FitImage] = {stem: get_image(stem, ICON_SIZE_DP) for stem, _ in UPGRADES}
        upgrades_grid = MDGridLayout(
            rows=UPGRADE_ROWS,
            padding=0,
            spacing=dp(2),
            size_hint_x=None,
            width=dp(-(-len(UPGRADES) // UPGRADE_ROWS) * (ICON_SIZE_DP + 2)),
        )
        for icon in self.upgrade_icons.values():
            upgrades_grid.add_widget(icon)
        self.layout.add_widget(upgrades_grid)

        self.update(compute_panel_state([], {}))

    def update(self, state: PanelState) -> None:
        for key, text in state.counters.items():
            self.counter_labels[key].text = text
        for stem, icon in self.upgrade_icons.items():
            icon.opacity = 1 if state.owned.get(stem, False) else 0.2
