"""The item-collection strip shown below the client window (mirrors
``worlds/metroidprime``'s MetroidPrimeClient panel): counters for tanks,
ammo and keys, plus a grid of every upgrade, dimmed until owned.

``compute_panel_state`` is pure (names in, display state out) so it can be
tested without kivy; ``build_panel`` is the thin kivy layer on top. Icons
live in ``assets/items`` and are generated by ``tools/make_tracker_icons.py``.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

from ..items import PROGRESSIVE_ITEMS
from .receive_items import compute_desired_capacities

if TYPE_CHECKING:
    from kivymd.uix.fitimage import FitImage

POWER_BOMB_SLOT = 43
MISSILE_LAUNCHER_FLAG_SLOT = 73

UNLIMITED = "∞"

# Counters with a fixed maximum are clamped to it: the server can resend items
# (e.g. the collect on goal completion), and a counter must never read past
# its max.
ENERGY_TANKS_TOTAL = 14
SKY_TEMPLE_KEYS_TOTAL = 9
DARK_TEMPLE_KEYS_TOTAL = 3

# (icon stem, item that lights it). Two rows of 16 in the window, so the
# first 16 are "combat" and the rest "exploration"; order within a row is
# the order in game menus.
UPGRADES: tuple[tuple[str, str], ...] = (
    ("powerbeam", "Power Beam"),
    ("darkbeam", "Dark Beam"),
    ("lightbeam", "Light Beam"),
    ("annihilatorbeam", "Annihilator Beam"),
    ("chargebeam", "Charge Beam"),
    ("supermissile", "Super Missile"),
    ("darkburst", "Darkburst"),
    ("sunburst", "Sunburst"),
    ("sonicboom", "Sonic Boom"),
    ("combatvisor", "Combat Visor"),
    ("scanvisor", "Scan Visor"),
    ("darkvisor", "Dark Visor"),
    ("echovisor", "Echo Visor"),
    ("variasuit", "Varia Suit"),
    ("darksuit", "Dark Suit"),
    ("lightsuit", "Light Suit"),
    ("morphball", "Morph Ball"),
    ("morphballbomb", "Morph Ball Bomb"),
    ("boostball", "Boost Ball"),
    ("spiderball", "Spider Ball"),
    ("powerbomb", "Power Bomb"),
    ("spacejumpboots", "Space Jump Boots"),
    ("gravityboost", "Gravity Boost"),
    ("grapplebeam", "Grapple Beam"),
    ("screwattack", "Screw Attack"),
    ("missilelauncher", "Missile Launcher"),
    ("seekerlauncher", "Seeker Launcher"),
    ("violettranslator", "Violet Translator"),
    ("ambertranslator", "Amber Translator"),
    ("emeraldtranslator", "Emerald Translator"),
    ("cobalttranslator", "Cobalt Translator"),
)

# (icon stem, counter key) in display order.
COUNTERS: tuple[tuple[str, str], ...] = (
    ("energytank", "energy_tanks"),
    ("missileexpansion", "missiles"),
    ("powerbombexpansion", "power_bombs"),
    ("darkammoexpansion", "dark_ammo"),
    ("lightammoexpansion", "light_ammo"),
    ("skytemplekey", "sky_temple_keys"),
    ("darkagonkey", "dark_agon_keys"),
    ("darktorvuskey", "dark_torvus_keys"),
    ("ingkey", "ing_hive_keys"),
)

# counter key -> expansion item it counts. Beam ammo expansions come in two
# shapes (split_beam_ammo): separate Dark/Light items, or one shared "Beam
# Ammo Expansion" that feeds both counters.
_EXPANSION_COUNTERS = {
    "energy_tanks": ("Energy Tank",),
    "missiles": ("Missile Expansion",),
    "power_bombs": ("Power Bomb Expansion",),
    "dark_ammo": ("Dark Ammo Expansion", "Beam Ammo Expansion"),
    "light_ammo": ("Light Ammo Expansion", "Beam Ammo Expansion"),
}

# icon stem -> tooltip text for the counter icons (upgrade icons use their
# item name from UPGRADES).
COUNTER_NAMES = {
    "energytank": "Energy Tanks",
    "missileexpansion": "Missile Expansions",
    "powerbombexpansion": "Power Bomb Expansions",
    "darkammoexpansion": "Dark Beam Ammo Expansions",
    "lightammoexpansion": "Light Beam Ammo Expansions",
    "skytemplekey": "Sky Temple Keys",
    "darkagonkey": "Dark Agon Keys",
    "darktorvuskey": "Dark Torvus Keys",
    "ingkey": "Ing Hive Keys",
}

_DARK_TEMPLE_KEY_PREFIXES = {
    "dark_agon_keys": "Dark Agon Key",
    "dark_torvus_keys": "Dark Torvus Key",
    "ing_hive_keys": "Ing Hive Key",
}


@dataclass
class PanelState:
    counters: dict[str, str] = field(default_factory=dict)
    owned: dict[str, bool] = field(default_factory=dict)
    """Keyed by icon stem."""


def _resolve_progressive(names: Iterable[str]) -> list[str]:
    """Replaces each Progressive item copy with the concrete item it
    currently represents (1st Progressive Suit -> Dark Suit, 2nd -> Light
    Suit, ...), so ownership checks below only ever see concrete names."""
    resolved: list[str] = []
    copies: dict[str, int] = {}
    for name in names:
        stages = PROGRESSIVE_ITEMS.get(name)
        if stages is None:
            resolved.append(name)
            continue
        index = copies.get(name, 0)
        copies[name] = index + 1
        resolved.append(stages[min(index, len(stages) - 1)])
    return resolved


def compute_panel_state(received_names: Iterable[str], slot_data: dict[str, Any]) -> PanelState:
    """``received_names`` is ``ctx.items_received`` mapped to item names, in
    receipt order (including the starting inventory)."""
    names = list(received_names)
    concrete = _resolve_progressive(names)
    have = set(concrete)

    # Launcher/Power Bomb unlocks and ammo totals come from the same model
    # that drives what the client actually grants, so the panel can't
    # disagree with the game.
    capacities = compute_desired_capacities(
        [(name, 0) for name in names],
        0,
        bool(slot_data.get("missile_expansions_unlock_launcher", False)),
        bool(slot_data.get("power_bomb_expansions_unlock_power_bombs", False)),
    )

    state = PanelState()
    for icon, item in UPGRADES:
        state.owned[icon] = item in have
    state.owned["missilelauncher"] = capacities.get(MISSILE_LAUNCHER_FLAG_SLOT, 0) > 0
    state.owned["powerbomb"] = capacities.get(POWER_BOMB_SLOT, 0) > 0

    # Expansion counters read "acquired/total". The totals are the pool sizes
    # (filler included) recorded in slot_data at generation; without them (an
    # older seed) the counter shows the bare acquired count.
    totals = slot_data.get("expansion_totals") or {}
    unlimited = {
        "missiles": "Unlimited Missiles" in have,
        "dark_ammo": "Unlimited Beam Ammo" in have,
        "light_ammo": "Unlimited Beam Ammo" in have,
    }
    for counter, item_names in _EXPANSION_COUNTERS.items():
        if unlimited.get(counter):
            state.counters[counter] = UNLIMITED
            continue
        acquired = sum(concrete.count(item) for item in item_names)
        total = sum(totals.get(item, 0) for item in item_names)
        if counter == "energy_tanks":
            # The game caps tanks at 14 however many are received.
            total = total or ENERGY_TANKS_TOTAL
            acquired = min(acquired, ENERGY_TANKS_TOTAL)
        state.counters[counter] = f"{min(acquired, total)}/{total}" if total else str(acquired)

    # Keys are unique items, so count distinct names: a repeated delivery of
    # the same key must not count twice.
    sky_keys = len({name for name in have if name.startswith("Sky Temple Key ")})
    required = slot_data.get("sky_temple_keys_required")
    if required:
        state.counters["sky_temple_keys"] = f"{min(sky_keys, required)}/{required}"
    else:
        state.counters["sky_temple_keys"] = str(min(sky_keys, SKY_TEMPLE_KEYS_TOTAL))
    for counter, prefix in _DARK_TEMPLE_KEY_PREFIXES.items():
        owned = len({name for name in have if name.startswith(prefix)})
        state.counters[counter] = f"{min(owned, DARK_TEMPLE_KEYS_TOTAL)}/{DARK_TEMPLE_KEYS_TOTAL}"

    return state


# --------------------------------------------------------------------------
# kivy layer
# --------------------------------------------------------------------------

ICON_SIZE_DP = 24
COUNTER_ICON_DP = 32
COUNTER_COLUMN_DP = COUNTER_ICON_DP + 8
PANEL_SPACING_DP = 2
PANEL_PADDING_DP = 5
UPGRADES_GAP_DP = 8
UPGRADE_ROWS = 2
UPGRADE_SPACING_DP = 2


def required_width_dp() -> int:
    """Width the panel needs to show every counter and upgrade; the window
    must be at least this wide (kivy's default 800 is too narrow)."""
    # Children: every counter column, a gap, then the upgrade grid.
    children = len(COUNTERS) + 2
    counters = len(COUNTERS) * COUNTER_COLUMN_DP
    upgrades = -(-len(UPGRADES) // UPGRADE_ROWS) * (ICON_SIZE_DP + UPGRADE_SPACING_DP)
    return 2 * PANEL_PADDING_DP + (children - 1) * PANEL_SPACING_DP + counters + UPGRADES_GAP_DP + upgrades


def _hover_image_class() -> type:
    """FitImage that shows a tooltip while hovered (same HoverBehavior +
    MDTooltip combination kvui's ServerLabel uses). Built lazily because
    kivy can only be imported once kvui has set it up."""
    global _HoverImage
    if _HoverImage is None:
        from kivymd.uix.fitimage import FitImage
        from kivymd.uix.tooltip import MDTooltip
        from kvui import HoverBehavior, ToolTip

        class HoverImage(HoverBehavior, MDTooltip, FitImage):
            tooltip_display_delay = 0.1

            def __init__(self, tooltip_text: str, **kwargs: Any) -> None:
                super().__init__(**kwargs)
                self._tooltip = ToolTip(text=tooltip_text)

            def on_enter(self) -> None:
                self.display_tooltip()

            def on_leave(self) -> None:
                self.animation_tooltip_dismiss()

        _HoverImage = HoverImage
    return _HoverImage


_HoverImage: type | None = None


def get_image(stem: str, size_dp: int, name: str) -> FitImage:
    from importlib import resources
    from io import BytesIO

    from kivy.core.image import Image
    from kivy.metrics import dp

    resource = resources.files(f"{__package__.rsplit('.', 1)[0]}.assets.items").joinpath(f"{stem}.png")
    texture = Image(BytesIO(resource.read_bytes()), ext="png").texture
    image = _hover_image_class()(tooltip_text=name, texture=texture)
    image.size_hint = (None, None)
    image.size = (dp(size_dp), dp(size_dp))
    image.fit_mode = "scale-down"
    return image


class ItemPanel:
    """Holds the kivy widgets; ``layout`` is what gets added to the window."""

    def __init__(self) -> None:
        from kivy.metrics import dp
        from kivy.uix.widget import Widget
        from kvui import MDBoxLayout, MDGridLayout, MDLabel

        self.layout = MDBoxLayout(
            orientation="horizontal",
            size_hint_y=None,
            height=dp(64),
            spacing=dp(PANEL_SPACING_DP),
            padding=dp(PANEL_PADDING_DP),
        )

        self.counter_labels: dict[str, MDLabel] = {}
        for stem, key in COUNTERS:
            column = MDGridLayout(
                rows=2,
                spacing=dp(3),
                size_hint_x=None,
                width=dp(COUNTER_COLUMN_DP),
                row_default_height=dp(COUNTER_ICON_DP),
                row_force_default=True,
            )
            icon = get_image(stem, COUNTER_ICON_DP, COUNTER_NAMES[stem])
            # Span the column so scale-down centers the icon over the (centered)
            # label instead of leaving it pinned to the cell's left edge.
            icon.size_hint_x = 1
            column.add_widget(icon)
            label = MDLabel(text="0", halign="center", valign="middle", role="medium")
            label.bind(size=lambda inst, val: setattr(inst, "text_size", val))
            column.add_widget(label)
            self.counter_labels[key] = label
            self.layout.add_widget(column)

        self.upgrade_icons: dict[str, FitImage] = {stem: get_image(stem, ICON_SIZE_DP, item) for stem, item in UPGRADES}
        upgrades_grid = MDGridLayout(
            rows=UPGRADE_ROWS,
            padding=0,
            spacing=dp(UPGRADE_SPACING_DP),
            size_hint_x=None,
            width=dp(-(-len(UPGRADES) // UPGRADE_ROWS) * (ICON_SIZE_DP + UPGRADE_SPACING_DP)),
        )
        for icon in self.upgrade_icons.values():
            upgrades_grid.add_widget(icon)
        self.layout.add_widget(Widget(size_hint_x=None, width=dp(UPGRADES_GAP_DP)))
        self.layout.add_widget(upgrades_grid)

        self.update(compute_panel_state([], {}))

    def update(self, state: PanelState) -> None:
        for key, text in state.counters.items():
            self.counter_labels[key].text = text
        for stem, icon in self.upgrade_icons.items():
            icon.opacity = 1 if state.owned.get(stem, False) else 0.2
