"""Player options for Metroid Prime 2: Echoes.

See ``PLAN.md`` section G. The 25 ``trick_<short_name>`` fields are
generated Choice classes from ``options_tricks.py`` (itself generated by
``tools/sync_randovania_data.py`` from the randovania logic database's
``resource_database.tricks``); they cannot be declared in a loop because
dataclass fields must be literal class-level annotations, so each is
written out explicitly below.
"""

from __future__ import annotations

from dataclasses import dataclass

from Options import (
    Choice,
    DeathLink,
    DefaultOnToggle,
    FreeText,
    OptionGroup,
    PerGameCommonOptions,
    Range,
    StartInventoryPool,
    Toggle,
    Visibility,
)

from .options_tricks import (
    TRICK_OPTION_NAMES,
    TrickAirUnderwater,
    TrickBombJump,
    TrickBomblessSlot,
    TrickBoostJump,
    TrickBSJ,
    TrickCombat,
    TrickDash,
    TrickEDash,
    TrickEnemyHop,
    TrickInstantMorph,
    TrickInvisibleObjects,
    TrickKnowledge,
    TrickMovement,
    TrickNoSuits,
    TrickOoB,
    TrickRollJump,
    TrickSAnoSJ,
    TrickScanPost,
    TrickScrewAttackTunnels,
    TrickSeekerlessLocks,
    TrickSlopeJump,
    TrickStandableTerrain,
    TrickTerminalFall,
    TrickUnderwaterDash,
    TrickWallBoost,
)

# --------------------------------------------------------------------------
# Goal / item pool options
# --------------------------------------------------------------------------


class SkyTempleKeys(Choice):
    """How many Sky Temple Keys are shuffled into the general item pool
    versus pre-placed or pre-collected.

    A number N puts keys 1..N into the general pool and pre-collects keys
    N+1..9 (0 means all 9 keys start collected -- an immediate escape to
    the credits once the Sky Temple Gateway is reached; 9, the default,
    puts every key into the pool like a normal item).

    All Bosses pre-places one key, in order, on each of the 9 boss/
    guardian pickup locations (the 6 "sub-guardians" plus the 3 dark
    temple guardians) instead of shuffling them into the pool.

    All Guardians pre-places keys 1-3 on the 3 dark temple guardians
    (Amorbis, Chykka, Quadraxis) and pre-collects keys 4-9.
    """

    display_name = "Sky Temple Keys"
    option_0 = 0
    option_1 = 1
    option_2 = 2
    option_3 = 3
    option_4 = 4
    option_5 = 5
    option_6 = 6
    option_7 = 7
    option_8 = 8
    option_9 = 9
    option_all_bosses = 10
    option_all_guardians = 11
    default = 9


class ProgressiveSuit(DefaultOnToggle):
    """If enabled, Dark Suit and Light Suit are combined into two copies of
    a single Progressive Suit item (first copy grants Dark Suit, second
    grants Light Suit)."""

    display_name = "Progressive Suit"


class ProgressiveGrapple(Toggle):
    """If enabled, Grapple Beam and Screw Attack are combined into two
    copies of a single Progressive Grapple item (first copy grants
    Grapple Beam, second grants Screw Attack)."""

    display_name = "Progressive Grapple"


# --------------------------------------------------------------------------
# Logic options
# --------------------------------------------------------------------------


class TrickLevel(Choice):
    """The default difficulty of tricks logic is allowed to require,
    applied to every trick that is left at "Use global setting" in its own
    per-trick option below. Disabled means no tricks are ever required."""

    display_name = "Trick Level"
    option_disabled = 0
    option_beginner = 1
    option_intermediate = 2
    option_advanced = 3
    option_expert = 4
    option_ludicrous = 5
    default = 0


class DamageStrictness(Choice):
    """How strictly damage requirements are calculated. Higher multipliers
    make logic assume incoming damage is larger (and thus require more
    energy tanks / better damage reduction before crossing a damaging
    area), matching randovania's "strict"/"medium"/"lenient" presets."""

    display_name = "Damage Strictness"
    option_strict = 0
    option_medium = 1
    option_lenient = 2
    default = 1


class EnergyPerTank(Range):
    """How much energy (health) each Energy Tank is worth."""

    display_name = "Energy Per Tank"
    range_start = 50
    range_end = 500
    default = 100


class DarkAetherDamage(Range):
    """Damage per second taken while in a dark world without appropriate
    suit protection, in TENTHS of a point per second (e.g. 60 == 6.0
    damage/second). ``Range`` is integer-only, so this and
    ``DarkSuitDamage`` are expressed in tenths rather than whole points --
    that's the only way to represent randovania's fractional Dark Suit
    default (1.2) exactly. Convert back to real damage/second units with
    ``dark_damage_per_second()`` below before using the value; never read
    ``.value`` directly for a damage calculation. The default of 60 (6.0
    damage/second) matches randovania's ``varia_suit_damage: 6.0``."""

    display_name = "Dark Aether Damage (tenths/second)"
    range_start = 10
    range_end = 600
    default = 60


class DarkSuitDamage(Range):
    """Damage per second taken while in a dark world with the Dark Suit
    (but not the Light Suit), in TENTHS of a point per second -- see
    ``DarkAetherDamage``'s docstring for why. The default of 12 (1.2
    damage/second) matches randovania's starter preset (``dark_suit_damage:
    1.2``) exactly; a plain integer ``Range`` in whole damage/second units
    could only default to 1 (~17% more permissive than randovania -- logic
    would assume less dark-aether damage than it should, an out-of-logic
    death risk) or 2 (stricter, but not what randovania actually uses)."""

    display_name = "Dark Suit Damage (tenths/second)"
    range_start = 0
    range_end = 600
    default = 12


class DangerousEnergyTanks(Toggle):
    """If enabled, some Energy Tanks may be placed in locations that
    themselves require surviving dark-world/damage requirements to reach,
    without another Energy Tank to make the trip safe."""

    display_name = "Dangerous Energy Tanks"


# --------------------------------------------------------------------------
# Entrance randomization
# --------------------------------------------------------------------------


class DoorLockRando(Toggle):
    """If enabled, certain door locks (beam-colored doors, blast shields)
    are shuffled among a vetted pool of lock types, instead of each door
    keeping its vanilla lock."""

    display_name = "Door Lock Randomization"


class ElevatorRando(Toggle):
    """If enabled, elevators are shuffled into new two-way connections
    (every region reachable via vanilla elevators stays reachable, but not
    necessarily through the same elevator), instead of vanilla
    connections. The one-way trip into Sky Temple and the intra-region
    Aerie elevator are never shuffled."""

    display_name = "Elevator Randomization"


class PortalRando(Toggle):
    """If enabled, the Light/Dark Aether portals (the fixed rift-travel
    pairs in Temple Grounds/Sky Temple Grounds, Agon Wastes/Dark Agon
    Wastes, Torvus Bog/Dark Torvus Bog, and Sanctuary Fortress/Ing Hive) are
    shuffled into new connections, within each light/dark region pair, and
    made two-way (every portal, including the vanilla one-way arrival-only
    ones, can be used in both directions -- open-prime-rando physically
    adds the missing return portal for those). Every portal keeps its own
    beam-color requirement; only where it leads changes."""

    display_name = "Portal Randomization"


class StartingRoom(Choice):
    """Which pool the starting room is drawn from (see
    ``logic/db_reader.py``'s ``GameDatabase.starting_location_candidates``
    for exactly what qualifies -- randovania's own
    ``valid_starting_location`` DB flag).

    Vanilla: always Temple Grounds/Landing Site, matching every seed
    generated before this option existed.
    Save Stations: one of the 18 save-station rooms across the whole game
    (9 in the 5 light regions, 9 in the 5 dark regions).
    Anywhere: one of 272 rooms -- every room randovania's DB considers a
    valid starting location (162 light / 110 dark), including e.g. boss
    arenas and rooms only normally reached via a one-way drop.

    A dark-world start (possible under either non-vanilla pool, unless
    ``starting_room_light_world_only`` is also enabled) means taking Dark
    Aether damage every second from the moment the game begins, until a
    suit or a safe zone is reached -- expect an immediately dangerous
    opening on some seeds.

    ``warp_to_start`` (see below) always returns to whichever room this
    picks; the decline-a-save warp itself only exists in the 18 save-station
    rooms (``can_warp_to_start``), regardless of which pool the actual
    start came from."""

    display_name = "Starting Room"
    option_vanilla = 0
    option_save_stations = 1
    option_anywhere = 2
    default = 0


class StartingRoomLightWorldOnly(Toggle):
    """If enabled, drops every dark-region room (Dark Agon Wastes, Dark
    Torvus Bog, Ing Hive, Sky Temple, Sky Temple Grounds) from whichever
    pool ``starting_room`` selects, guaranteeing a light-world (no Dark
    Aether damage) start. No effect when ``starting_room`` is left at
    Vanilla -- Landing Site is already a light-world room."""

    display_name = "Starting Room: Light World Only"


class TranslatorGateRando(Choice):
    """How each of the 17 translator gates' required color is chosen,
    matching randovania's own translator gate presets.

    Vanilla: every gate requires its vanilla translator color.
    Random: every gate independently requires a random one of the four
    translator colors (Violet/Amber/Emerald/Cobalt).
    Random (Unlocked): like Random, but each gate may also independently
    come up "Unlocked" -- open with just Scan Visor, no translator
    required at all."""

    display_name = "Translator Gate Randomization"
    option_vanilla = 0
    option_full_random = 1
    option_full_random_unlocked = 2
    default = 0


# --------------------------------------------------------------------------
# Cosmetic options
# --------------------------------------------------------------------------


class DisplayNonLocalItems(Choice):
    """How items belonging to other worlds are displayed in-game.

    None: only this world's own items get matching in-game models; every
    other item shows as a generic Energy Transfer Module.
    Match Game: items belonging to another Metroid Prime 2: Echoes player
    also get a matching model."""

    display_name = "Display Non-Local Items"
    option_none = 0
    option_match_game = 1
    default = 1


class UnvisitedRoomNames(DefaultOnToggle):
    """If enabled, the map shows room names for rooms that have not been
    visited yet."""

    display_name = "Unvisited Room Names"


class MapVisibility(Choice):
    """How much of the in-game map is revealed from the start.

    `vanilla`: the map fills in as you explore, and an item's dot appears
    only once its room has been visited or its map station used.

    `full_map`: every room is drawn from the start (rooms still need to be
    visited to show their name/details), but item dots still wait for their
    room to be visited.

    `full_map_and_items`: as `full_map`, plus a dot at every item location
    from the start, mirroring the Metroid Prime 1 randomizer.

    These are one setting rather than two toggles because an item dot needs
    its room drawn to be visible at all -- "item dots without the revealed
    map" would be indistinguishable from `vanilla`.
    """

    display_name = "Map Visibility"
    option_vanilla = 0
    option_full_map = 1
    option_full_map_and_items = 2
    default = 0



class RevealMapRemoved(FreeText):
    """Removed: ``reveal_map`` was folded into ``map_visibility`` (PLAN.md
    section M). Present only so an old YAML that still sets it says so.

    Deliberately *not* a plain ``Options.Removed``: that class rejects any
    value once ``FreeText.from_any`` has stringified it (``cls(str(data))``
    -- so YAML's ``false`` arrives as the truthy string ``"False"``), and
    ``reveal_map: false`` is the line 1.0.0's own
    ``example_world_config.yaml`` shipped. Failing generation for every
    YAML copied from it would be noise: ``false`` means exactly what
    ``map_visibility``'s ``vanilla`` default now means, so nothing is lost.
    Only a value that actually asked for a revealed map loses information,
    so only that is an error.
    """

    visibility = Visibility.none
    default = ""

    # Everything YAML/AP can hand over for a "no" answer, lowercased:
    # absent (the "" default), false, 0, none, off.
    _NOTHING_TO_SAY = frozenset({"", "false", "0", "none", "off"})

    def __init__(self, value: str) -> None:
        if str(value).strip().lower() not in self._NOTHING_TO_SAY:
            raise Exception(
                "`reveal_map` has been replaced by `map_visibility`: use "
                "`map_visibility: full_map`, or `full_map_and_items` to also show "
                "every item location on the map. Then delete the `reveal_map` line."
            )
        super().__init__("")


class WarpToStart(DefaultOnToggle):
    """If enabled, declining to save at any Save Station while holding L+R
    warps you back to the starting room (Samus' ship in Landing Site).

    Mirrors the same feature in the Metroid Prime 1 randomizer. Declining
    without holding L+R behaves exactly as it does in vanilla."""

    display_name = "Warp to Start"


class MissileExpansionsUnlockLauncher(Toggle):
    """If enabled, receiving any Missile Expansion also unlocks the Missile
    Launcher itself, so expansions are usable without finding the launcher.

    Off (the default) matches Randovania: Missile Expansions grant nothing
    until the Missile Launcher is collected. The setting affects logic as
    well as the in-game grant, so an expansion counts toward missile
    requirements when it is on.
    """

    display_name = "Missile Expansions Unlock Launcher"


@dataclass
class MetroidPrime2Options(PerGameCommonOptions):
    start_inventory_from_pool: StartInventoryPool

    sky_temple_keys: SkyTempleKeys
    progressive_suit: ProgressiveSuit
    progressive_grapple: ProgressiveGrapple
    missile_expansions_unlock_launcher: MissileExpansionsUnlockLauncher

    trick_level: TrickLevel
    trick_airunderwater: TrickAirUnderwater
    trick_bsj: TrickBSJ
    trick_bombjump: TrickBombJump
    trick_bomblessslot: TrickBomblessSlot
    trick_boostjump: TrickBoostJump
    trick_combat: TrickCombat
    trick_dash: TrickDash
    trick_edash: TrickEDash
    trick_enemyhop: TrickEnemyHop
    trick_instantmorph: TrickInstantMorph
    trick_invisibleobjects: TrickInvisibleObjects
    trick_knowledge: TrickKnowledge
    trick_movement: TrickMovement
    trick_nosuits: TrickNoSuits
    trick_oob: TrickOoB
    trick_rolljump: TrickRollJump
    trick_sanosj: TrickSAnoSJ
    trick_scanpost: TrickScanPost
    trick_screwattacktunnels: TrickScrewAttackTunnels
    trick_seekerlesslocks: TrickSeekerlessLocks
    trick_slopejump: TrickSlopeJump
    trick_standableterrain: TrickStandableTerrain
    trick_terminalfall: TrickTerminalFall
    trick_underwaterdash: TrickUnderwaterDash
    trick_wallboost: TrickWallBoost

    damage_strictness: DamageStrictness
    energy_per_tank: EnergyPerTank
    dark_aether_damage: DarkAetherDamage
    dark_suit_damage: DarkSuitDamage
    dangerous_energy_tanks: DangerousEnergyTanks

    door_lock_rando: DoorLockRando
    elevator_rando: ElevatorRando
    portal_rando: PortalRando
    translator_gate_rando: TranslatorGateRando
    starting_room: StartingRoom
    starting_room_light_world_only: StartingRoomLightWorldOnly

    warp_to_start: WarpToStart

    display_nonlocal_items: DisplayNonLocalItems
    map_visibility: MapVisibility
    unvisited_room_names: UnvisitedRoomNames

    death_link: DeathLink

    # Folded into map_visibility (PLAN.md section M). Shipped in 1.0.0, so
    # this shim makes an old YAML's `reveal_map: true` fail with a message
    # naming its replacement instead of being silently dropped, while
    # `reveal_map: false` -- what the 1.0.0 example config shipped, and
    # equivalent to map_visibility's `vanilla` default -- still generates.
    reveal_map: RevealMapRemoved


OPTION_GROUPS: list[OptionGroup] = [
    OptionGroup("Goal", [SkyTempleKeys]),
    OptionGroup(
        "Item Pool", [ProgressiveSuit, ProgressiveGrapple, MissileExpansionsUnlockLauncher]
    ),
    OptionGroup(
        "Logic",
        [
            TrickLevel,
            DamageStrictness,
            EnergyPerTank,
            DarkAetherDamage,
            DarkSuitDamage,
            DangerousEnergyTanks,
        ],
    ),
    OptionGroup(
        "Entrances",
        [
            DoorLockRando,
            ElevatorRando,
            PortalRando,
            TranslatorGateRando,
            StartingRoom,
            StartingRoomLightWorldOnly,
        ],
    ),
    OptionGroup(
        "Tricks",
        [
            TrickAirUnderwater,
            TrickBSJ,
            TrickBombJump,
            TrickBomblessSlot,
            TrickBoostJump,
            TrickCombat,
            TrickDash,
            TrickEDash,
            TrickEnemyHop,
            TrickInstantMorph,
            TrickInvisibleObjects,
            TrickKnowledge,
            TrickMovement,
            TrickNoSuits,
            TrickOoB,
            TrickRollJump,
            TrickSAnoSJ,
            TrickScanPost,
            TrickScrewAttackTunnels,
            TrickSeekerlessLocks,
            TrickSlopeJump,
            TrickStandableTerrain,
            TrickTerminalFall,
            TrickUnderwaterDash,
            TrickWallBoost,
        ],
        start_collapsed=True,
    ),
    OptionGroup("Quality of Life", [WarpToStart]),
    OptionGroup(
        "Cosmetic",
        [DisplayNonLocalItems, MapVisibility, UnvisitedRoomNames],
    ),
]


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------

# Trick difficulty levels: 0 disabled .. 5 ludicrous, matching TrickLevel
# and every per-trick Choice's option_* values shifted by 1 (option_disabled
# = 1 there because 0 is reserved for "use_global").
_MAX_TRICK_LEVEL = 5


def trick_levels_from_options(options: MetroidPrime2Options) -> dict[str, int]:
    """Map each DB trick short_name to its effective 0..5 difficulty level.

    For each trick, the per-trick option (``trick_<short_name>``) wins
    when set to anything but "use_global" (0); otherwise the global
    ``trick_level`` option applies.
    """
    global_level = options.trick_level.value
    levels: dict[str, int] = {}
    for short_name, field_name in TRICK_OPTION_NAMES.items():
        per_trick = getattr(options, field_name).value
        levels[short_name] = global_level if per_trick == 0 else per_trick - 1
    return levels


# damage_strictness option value -> randovania multiplier.
_DAMAGE_STRICTNESS_MULTIPLIERS = {
    DamageStrictness.option_strict: 1.0,
    DamageStrictness.option_medium: 1.5,
    DamageStrictness.option_lenient: 2.0,
}


def damage_strictness_multiplier(options: MetroidPrime2Options) -> float:
    return _DAMAGE_STRICTNESS_MULTIPLIERS[options.damage_strictness.value]


# DarkAetherDamage/DarkSuitDamage are stored in tenths of a point per second
# (see their docstrings); every call site (logic and the ISO patcher alike)
# needs real damage/second units, so they share this one conversion instead
# of each re-deriving the /10.0 scale factor.
def dark_damage_per_second(option_value_tenths: int) -> float:
    return option_value_tenths / 10.0
