"""Player options for Metroid Prime 2: Echoes.

See ``PLAN.md`` section G. The 25 ``trick_<short_name>`` fields are
generated Choice classes from ``options_tricks.py`` (itself generated by
``tools/sync_randovania_data.py`` from the randovania logic database's
``resource_database.tricks``); they cannot be declared in a loop because
dataclass fields must be literal class-level annotations, so each is
written out explicitly below.
"""

from __future__ import annotations

from dataclasses import dataclass

from Options import (
    Choice,
    DeathLink,
    DefaultOnToggle,
    FreeText,
    OptionGroup,
    PerGameCommonOptions,
    Range,
    StartInventoryPool,
    Toggle,
    Visibility,
)

from .options_tricks import (
    TRICK_OPTION_NAMES,
    TrickAirUnderwater,
    TrickBombJump,
    TrickBomblessSlot,
    TrickBoostJump,
    TrickBSJ,
    TrickCombat,
    TrickDash,
    TrickEDash,
    TrickEnemyHop,
    TrickInstantMorph,
    TrickInvisibleObjects,
    TrickKnowledge,
    TrickMovement,
    TrickNoSuits,
    TrickOoB,
    TrickRollJump,
    TrickSAnoSJ,
    TrickScanPost,
    TrickScrewAttackTunnels,
    TrickSeekerlessLocks,
    TrickSlopeJump,
    TrickStandableTerrain,
    TrickTerminalFall,
    TrickUnderwaterDash,
    TrickWallBoost,
)
from . import constants

# --------------------------------------------------------------------------
# Goal / item pool options
# --------------------------------------------------------------------------


class Goal(Choice):
    """Which boss(es) must fall before the multiworld considers this slot's
    game complete.

    The two boss-skipping goals patch your game to warp you straight to the
    Credits (which reports the goal) the moment they are met. Both Bosses
    patches nothing.

    Both Bosses (default, vanilla): complete once the Credits are reached,
    which requires defeating both Emperor Ing (Sky Temple/Sanctum) and
    Dark Samus 3 & 4 (Sky Temple Gateway), exactly like an unmodified
    playthrough.

    Emperor Ing: complete once Emperor Ing is defeated and you return to
    Sky Temple Gateway, where you are warped to the Credits instead of
    fighting Dark Samus 3 & 4.

    Keys: complete as soon as Sky Temple Energy Controller is reached --
    which only requires opening the Sky Temple Gateway's key gate (see
    ``sky_temple_keys_required``) -- without fighting either boss. You are
    warped to the Credits from there.
    """

    display_name = "Goal"
    option_both_bosses = constants.GOAL_BOTH_BOSSES
    option_emperor_ing = constants.GOAL_EMPEROR_ING
    option_keys = constants.GOAL_KEYS
    default = option_both_bosses


class SkyTempleKeys(Range):
    """How many of the 9 Sky Temple Keys are real, findable items --
    shuffled into the general pool, or pre-placed on a boss/guardian per
    ``sky_temple_keys_locations`` -- versus starting the game already
    pre-collected for free.

    0 means all 9 keys start pre-collected -- an immediate escape to the
    credits once the Sky Temple Gateway is reached. 9, the default, makes
    every key findable, the same as a normal item.
    """

    display_name = "Sky Temple Keys"
    range_start = 0
    range_end = 9
    default = 9


class SkyTempleKeysLocations(Choice):
    """Where the findable Sky Temple Keys (see ``sky_temple_keys``) are
    placed.

    Off (default): keys are shuffled into the general item pool like any
    other progression item. Works with any ``sky_temple_keys`` value.

    All Bosses pre-places one key, in order, on each of the 9 boss/
    guardian pickup locations (the 6 "sub-guardians" plus the 3 dark
    temple guardians) instead of shuffling them into the pool. Requires
    ``sky_temple_keys`` to be 9.

    All Guardians pre-places the first 3 keys on the 3 dark temple
    guardians (Amorbis, Chykka, Quadraxis); any further findable keys
    (``sky_temple_keys`` minus 3) are shuffled into the general pool, the
    same as Off. Requires ``sky_temple_keys`` to be at least 3.
    """

    display_name = "Sky Temple Keys Locations"
    option_off = 0
    option_all_bosses = 1
    option_all_guardians = 2
    default = option_off


class SkyTempleKeysRequired(Range):
    """How many Sky Temple Keys must actually be held to unlock the Sky
    Temple Gateway's ring of columns and proceed to the Dark Samus 3/4
    fight, independent of where (or whether) ``sky_temple_keys`` makes
    them findable.

    Vanilla (and this option's default) requires all 9. A lower value is
    a real difficulty reduction, not just a relocation: with
    ``sky_temple_keys`` at 9 and this at, say, 6, only 6 of the 9 key
    locations ever need to be found before the Gateway opens -- the
    remaining 3 keys still exist and can still be found (nothing is
    removed from the pool), they simply stop being necessary.

    Must be no higher than ``sky_temple_keys`` -- a value higher than that
    could never be satisfied, since it's impossible to hold more keys than
    are findable. Silently clamped down to ``sky_temple_keys`` if higher.
    See ``item_pool.sky_temple_keys_required_count``.
    """

    display_name = "Sky Temple Keys Required"
    range_start = 1
    range_end = 9
    default = 9


class SkyTempleKeyHints(Choice):
    """Whether the 9 Luminoth pillars in Sky Temple Gateway hint at where
    each Sky Temple Key really is.

    Scanned (default): scanning a pillar shows where that key is (your own
    world or another player's) and sends the hint to the server, the same
    as any other in-game hint.
    Precollected: every key hint is known from the start (sent to the
    server as soon as the game begins), without needing to scan anything.
    Disabled: the pillars' text is replaced with a non-hint
    ("... is lost somewhere in Aether.") instead -- the vanilla riddles
    describe vanilla key spots and would mislead once keys are shuffled.
    """

    display_name = "Sky Temple Key Hints"
    option_disabled = 0
    option_scanned = 1
    option_precollected = 2
    default = option_scanned
    alias_false = option_disabled
    alias_true = option_scanned


class TranslatorLoreHints(Choice):
    """Whether the 22 colored Luminoth lore holograms hint at where a
    progression item can be found, the same way the Sky Temple Key
    pillars do (``sky_temple_key_hints``) -- scanning one to completion
    sends the hint to the server.

    My Items (default): each hologram names where one of YOUR OWN
    progression items is, in any player's world.
    Any: the pool also includes other players' progression items that
    landed in YOUR OWN world (the most a hologram is allowed to hint at
    someone else's item).
    Off: holograms keep their vanilla lore text; nothing is hinted.

    Only progression items are ever chosen, excluding Missile/Power Bomb/
    Dark/Light/Beam Ammo Expansions, Energy Tanks, and Sky Temple Keys --
    all indistinguishable-copy bulk items where "one of them is at
    location X" isn't useful (Sky Temple Keys are left entirely to the
    pillars above, see `sky_temple_key_hints`). Each remaining item is
    hinted at most once. If there are fewer eligible items than holograms,
    the extra holograms simply say there's nothing more to tell.
    """

    display_name = "Translator Lore Hints"
    option_off = 0
    option_my_items = 1
    option_any = 2
    default = option_my_items


class TranslatorLoreRando(Choice):
    """How each of the 22 Luminoth lore holograms' required translator
    color is chosen. The hologram (and its glow) is recolored to match, so
    you can still tell at a glance which translator reads it.

    Vanilla: every hologram requires its vanilla translator (Violet in
    Temple Grounds/Great Temple, Amber in Agon Wastes, Emerald in Torvus
    Bog, Cobalt in Sanctuary Fortress).
    Random: every hologram independently requires a random one of the four
    translator colors.

    Only changes which translator a hologram needs; what it says is still
    controlled by `translator_lore_hints`."""

    display_name = "Translator Lore Randomization"
    option_vanilla = 0
    option_full_random = 1
    default = option_vanilla


class ProgressiveSuit(DefaultOnToggle):
    """If enabled, Dark Suit and Light Suit are combined into two copies of
    a single Progressive Suit item (first copy grants Dark Suit, second
    grants Light Suit)."""

    display_name = "Progressive Suit"


class ProgressiveGrapple(Toggle):
    """If enabled, Grapple Beam and Screw Attack are combined into two
    copies of a single Progressive Grapple item (first copy grants
    Grapple Beam, second grants Screw Attack)."""

    display_name = "Progressive Grapple"


# --------------------------------------------------------------------------
# Logic options
# --------------------------------------------------------------------------


class TrickLevel(Choice):
    """The default difficulty of tricks logic is allowed to require,
    applied to every trick that is left at "Use global setting" in its own
    per-trick option below. Disabled means no tricks are ever required."""

    display_name = "Trick Level"
    option_disabled = 0
    option_beginner = 1
    option_intermediate = 2
    option_advanced = 3
    option_expert = 4
    option_ludicrous = 5
    default = 0


class DamageStrictness(Choice):
    """How strictly damage requirements are calculated. Higher multipliers
    make logic assume incoming damage is larger (and thus require more
    energy tanks / better damage reduction before crossing a damaging
    area), matching randovania's "strict"/"medium"/"lenient" presets."""

    display_name = "Damage Strictness"
    option_strict = 0
    option_medium = 1
    option_lenient = 2
    default = 1


class EnergyPerTank(Range):
    """How much energy (health) each Energy Tank is worth."""

    display_name = "Energy Per Tank"
    range_start = 50
    range_end = 500
    default = 100


class MaxEnergyTanks(Range):
    """EXPERIMENTAL. The most Energy Tanks you can hold. The vanilla game
    caps this at 14; higher values rewrite the game's item cap at patch
    time. The in-game HUD only has room for 14 tank icons, so extra tanks
    may not be drawn (the energy readout is still correct). Logic assumes
    this many tanks are usable."""

    display_name = "Max Energy Tanks"
    range_start = 14
    range_end = 99
    default = 14


class DarkAetherDamage(Range):
    """Damage per second taken while in a dark world without appropriate
    suit protection, in TENTHS of a point per second (e.g. 60 == 6.0
    damage/second). ``Range`` is integer-only, so this and
    ``DarkSuitDamage`` are expressed in tenths rather than whole points --
    that's the only way to represent randovania's fractional Dark Suit
    default (1.2) exactly. Convert back to real damage/second units with
    ``dark_damage_per_second()`` below before using the value; never read
    ``.value`` directly for a damage calculation. The default of 60 (6.0
    damage/second) matches randovania's ``varia_suit_damage: 6.0``."""

    display_name = "Dark Aether Damage (tenths/second)"
    range_start = 10
    range_end = 600
    default = 60


class DarkSuitDamage(Range):
    """Damage per second taken while in a dark world with the Dark Suit
    (but not the Light Suit), in TENTHS of a point per second -- see
    ``DarkAetherDamage``'s docstring for why. The default of 12 (1.2
    damage/second) matches randovania's starter preset (``dark_suit_damage:
    1.2``) exactly; a plain integer ``Range`` in whole damage/second units
    could only default to 1 (~17% more permissive than randovania -- logic
    would assume less dark-aether damage than it should, an out-of-logic
    death risk) or 2 (stricter, but not what randovania actually uses)."""

    display_name = "Dark Suit Damage (tenths/second)"
    range_start = 0
    range_end = 600
    default = 12


class DangerousEnergyTanks(Toggle):
    """If enabled, some Energy Tanks may be placed in locations that
    themselves require surviving dark-world/damage requirements to reach,
    without another Energy Tank to make the trip safe."""

    display_name = "Dangerous Energy Tanks"


# --------------------------------------------------------------------------
# Entrance randomization
# --------------------------------------------------------------------------


class DoorLockRando(Toggle):
    """If enabled, certain door locks (beam-colored doors, blast shields)
    are shuffled among a vetted pool of lock types, instead of each door
    keeping its vanilla lock."""

    display_name = "Door Lock Randomization"


class NormalSaveStationDoors(DefaultOnToggle):
    """If enabled, door lock randomization never puts a restrictive lock on
    a room containing a Save Station: every door of such a room -- and the
    matching face on the far side, which is the one you shoot to get in --
    is forced to a Normal Door (opens with any beam).

    On by default so a save station is always reachable with whatever beam
    you have. Because both faces of a physical door must agree, this also
    makes the neighbouring room's side of that door normal.

    Note this can also *remove* a lock the vanilla game had: a few save
    rooms ship with a Missile Blast Shield or Dark Door, and those are
    normalized too rather than merely left un-randomized.

    No effect unless `door_lock_rando` is on.
    """

    display_name = "Normal Save Station Doors"


class ElevatorRando(Toggle):
    """If enabled, elevators are shuffled into new two-way connections
    (every region reachable via vanilla elevators stays reachable, but not
    necessarily through the same elevator), instead of vanilla
    connections. The one-way trip into Sky Temple and the intra-region
    Aerie elevator are never shuffled."""

    display_name = "Elevator Randomization"


class PortalRando(Toggle):
    """If enabled, the Light/Dark Aether portals (the fixed rift-travel
    pairs in Temple Grounds/Sky Temple Grounds, Agon Wastes/Dark Agon
    Wastes, Torvus Bog/Dark Torvus Bog, and Sanctuary Fortress/Ing Hive) are
    shuffled into new connections, within each light/dark region pair, and
    made two-way (every portal, including the vanilla one-way arrival-only
    ones, can be used in both directions -- open-prime-rando physically
    adds the missing return portal for those). Every portal keeps its own
    beam-color requirement; only where it leads changes."""

    display_name = "Portal Randomization"


class StartingRoom(Choice):
    """Which pool the starting room is drawn from (see
    ``logic/db_reader.py``'s ``GameDatabase.starting_location_candidates``
    for exactly what qualifies -- randovania's own
    ``valid_starting_location`` DB flag).

    Vanilla: always Temple Grounds/Landing Site, matching every seed
    generated before this option existed.
    Save Stations: one of the 18 save-station rooms across the whole game
    (9 in the 5 light regions, 9 in the 5 dark regions).
    Anywhere: one of 272 rooms -- every room randovania's DB considers a
    valid starting location (162 light / 110 dark), including e.g. boss
    arenas and rooms only normally reached via a one-way drop.

    A dark-world start (possible under either non-vanilla pool, unless
    ``starting_room_light_world_only`` is also enabled) means taking Dark
    Aether damage every second from the moment the game begins, until a
    suit or a safe zone is reached -- expect an immediately dangerous
    opening on some seeds.

    ``warp_to_start`` (see below) always returns to whichever room this
    picks; the decline-a-save warp itself only exists in the 18 save-station
    rooms (``can_warp_to_start``), regardless of which pool the actual
    start came from."""

    display_name = "Starting Room"
    option_vanilla = 0
    option_save_stations = 1
    option_anywhere = 2
    default = 0


class StartingRoomLightWorldOnly(Toggle):
    """If enabled, drops every dark-region room (Dark Agon Wastes, Dark
    Torvus Bog, Ing Hive, Sky Temple, Sky Temple Grounds) from whichever
    pool ``starting_room`` selects, guaranteeing a light-world (no Dark
    Aether damage) start. No effect when ``starting_room`` is left at
    Vanilla -- Landing Site is already a light-world room."""

    display_name = "Starting Room: Light World Only"


class TranslatorGateRando(Choice):
    """How each of the 17 translator gates' required color is chosen,
    matching randovania's own translator gate presets.

    Vanilla: every gate requires its vanilla translator color.
    Random: every gate independently requires a random one of the four
    translator colors (Violet/Amber/Emerald/Cobalt).
    Random (Unlocked): like Random, but each gate may also independently
    come up "Unlocked" -- open with just Scan Visor, no translator
    required at all."""

    display_name = "Translator Gate Randomization"
    option_vanilla = 0
    option_full_random = 1
    option_full_random_unlocked = 2
    default = 0


# --------------------------------------------------------------------------
# Cosmetic options
# --------------------------------------------------------------------------


class DisplayNonLocalItems(Choice):
    """How items belonging to other worlds are displayed in-game.

    None: only this world's own items get matching in-game models; every
    other item shows as a generic Energy Transfer Module.
    Match Game: items belonging to another Metroid Prime 2: Echoes player
    also get a matching model, and so do conceptually-equivalent items
    from MultiWorldGG's other Metroid games (Metroid Prime, Metroid: Zero
    Mission, Metroid Fusion, Super Metroid) -- e.g. a Metroid Prime Energy
    Tank or a Super Metroid Missile shows up as this game's own Energy
    Tank/Missile Expansion model (see ``patch_data.py``'s
    ``_CROSS_GAME_ITEM_NAMES``). A handful of these cross-game matches
    (and the Metroid Prime Missile Expansion reskin,
    ``_CROSS_GAME_MODEL_OVERRIDES``) are experimental: they resolve to a
    model this world has never independently verified is safe to place
    outside its own default spot, the same category of open-prime-rando
    defect that made the "Varia Suit" model (never matched, on any game)
    crash the game elsewhere. Anything without a curated match (or from a
    game not in that list) still falls back to the generic model."""

    display_name = "Display Non-Local Items"
    option_none = 0
    option_match_game = 1
    default = 1


class UnvisitedRoomNames(DefaultOnToggle):
    """If enabled, the map shows room names for rooms that have not been
    visited yet."""

    display_name = "Unvisited Room Names"


class MapVisibility(Choice):
    """How much of the in-game map is revealed from the start.

    `vanilla`: the map fills in as you explore.

    `full_map`: every room is drawn from the start (rooms still need to be
    visited to show their name/details).

    Item dots are a separate option, `item_map_dots`. `full_map_and_items`
    is still accepted, as an alias of `full_map`.
    """

    display_name = "Map Visibility"
    option_vanilla = 0
    option_full_map = 1
    # Was its own value, meant to show every item dot from the start; it
    # never drew anything (PLAN.md section M). Kept so old YAMLs generate.
    alias_full_map_and_items = 1
    default = 0


class ItemMapDots(DefaultOnToggle):
    """If enabled, every item location shows as a dot on the map and
    minimap once its room has been visited or revealed by a map station
    (the same rule door icons follow). A dot disappears once its item is
    collected. A map revealed from the start by `map_visibility` doesn't
    reveal the dots.

    If disabled, no item dots are ever shown."""

    display_name = "Item Map Dots"


class RevealMapRemoved(FreeText):
    """Removed: ``reveal_map`` was folded into ``map_visibility`` (PLAN.md
    section M). Present only so an old YAML that still sets it says so.

    Deliberately *not* a plain ``Options.Removed``: that class rejects any
    value once ``FreeText.from_any`` has stringified it (``cls(str(data))``
    -- so YAML's ``false`` arrives as the truthy string ``"False"``), and
    ``reveal_map: false`` is the line 1.0.0's own
    ``example_world_config.yaml`` shipped. Failing generation for every
    YAML copied from it would be noise: ``false`` means exactly what
    ``map_visibility``'s ``vanilla`` default now means, so nothing is lost.
    Only a value that actually asked for a revealed map loses information,
    so only that is an error.
    """

    visibility = Visibility.none
    default = ""

    # Everything YAML/AP can hand over for a "no" answer, lowercased:
    # absent (the "" default), false, 0, none, off.
    _NOTHING_TO_SAY = frozenset({"", "false", "0", "none", "off"})

    def __init__(self, value: str) -> None:
        if str(value).strip().lower() not in self._NOTHING_TO_SAY:
            raise Exception(
                "`reveal_map` has been replaced by `map_visibility`: use "
                "`map_visibility: full_map`. Then delete the `reveal_map` line."
            )
        super().__init__("")


class WarpToStart(DefaultOnToggle):
    """If enabled, declining to save at any Save Station while holding L+R
    warps you back to the starting room (Samus' ship in Landing Site).

    Mirrors the same feature in the Metroid Prime 1 randomizer. Declining
    without holding L+R behaves exactly as it does in vanilla."""

    display_name = "Warp to Start"


class PreScanElevators(DefaultOnToggle):
    """If enabled, elevators start pre-scanned so you don't need to scan the
    hologram pillar before using them. Mirrors the same feature in the
    Metroid Prime 1 randomizer. Purely cosmetic/QoL: Scan Visor is always
    a starting item and elevators are never logically gated on it, so
    disabling this only affects whether you have to scan first."""

    display_name = "Pre-Scan Elevators"


class MoveWhileScanning(Toggle):
    """If enabled, you can move while Scan Visor is locked onto a scan
    point, instead of the game freezing your movement for the duration of
    the scan.

    Mirrors the Metroid Prime 1 randomizer's (undocumented) "move while
    scan" setting. Purely cosmetic/QoL: logic never assumes you can move
    during a scan either way."""

    display_name = "Move While Scanning"


class SpringBall(Toggle):
    """If enabled, once you have Morph Ball Bombs you can jump in Morph Ball
    by pressing a button (see `spring_ball_button`), without laying a bomb.
    The jump is the same height as a bomb jump, and only works on the
    ground.

    Mirrors the Metroid Prime 1 randomizer's spring ball "when bombs
    acquired" setting. Logic never requires it: everything it can reach is
    already reachable with Morph Ball Bombs."""

    display_name = "Spring Ball"


class SpringBallButton(Choice):
    """The button that triggers `spring_ball` while in Morph Ball. None of
    these do anything in vanilla Morph Ball. The C-Stick directions trigger
    at the same deflection the game uses for its own digital stick inputs.
    L Trigger means pressing it fully, past the click."""

    display_name = "Spring Ball Button"
    option_c_stick_up = 0
    option_c_stick_down = 1
    option_c_stick_left = 2
    option_c_stick_right = 3
    option_d_pad_up = 4
    option_l_trigger = 5
    default = option_c_stick_up


class MissileExpansionsUnlockLauncher(Toggle):
    """If enabled, receiving any Missile Expansion also unlocks the Missile
    Launcher itself, so expansions are usable without finding the launcher.

    Off (the default) matches Randovania: Missile Expansions grant nothing
    until the Missile Launcher is collected. The setting affects logic as
    well as the in-game grant, so an expansion counts toward missile
    requirements when it is on.
    """

    display_name = "Missile Expansions Unlock Launcher"


class PowerBombExpansionsUnlockPowerBombs(Toggle):
    """If enabled, receiving any Power Bomb Expansion also unlocks Power
    Bombs themselves, so expansions are usable without finding the main
    Power Bomb pickup.

    Off (the default) matches Randovania: Power Bomb Expansions grant
    nothing until the Power Bomb pickup is collected. The setting affects
    logic as well as the in-game grant, so an expansion counts toward
    Power Bomb requirements when it is on.

    The Missile counterpart is `missile_expansions_unlock_launcher`; the
    two are independent (either combination is meaningful).
    """

    display_name = "Power Bomb Expansions Unlock Power Bombs"


class SplitBeamAmmo(DefaultOnToggle):
    """If enabled (the default, matching vanilla and Randovania's own
    default), Dark Ammo and Light Ammo are collected as two separate
    expansion types: 10 Dark Ammo Expansions and 10 Light Ammo Expansions,
    each granting 20 of their own ammo type.

    If disabled, both ammo types are instead collected together from a
    single unified pickup type -- Randovania's "Beam Ammo Expansion" (its
    GUI calls this option "Split Beam Ammo Expansions", inverted): 20 Beam
    Ammo Expansions, each granting 10 Dark Ammo and 10 Light Ammo. The
    total ammo economy is identical either way (200 Dark + 200 Light
    across 20 pickups); only how it's split across pickups changes. Open-
    prime-rando already ships the combined pickup model this needs
    (`BeamAmmoExpansion`)."""

    display_name = "Split Beam Ammo Expansions"


class BeamAmmoCosts(Choice):
    """How much Dark Ammo / Light Ammo each shot of the Dark Beam, Light
    Beam, and Annihilator Beam costs (open-prime-rando's per-beam
    ``BeamConfiguration``). Vanilla costs 1 ammo per uncharged shot, 5 per
    charged shot, and 30 per charge combo (plus 5 missiles) -- identical
    across all three beams.

    Vanilla: unchanged. Cheap: uncharged/charged/combo-ammo costs halved
    (combo missile cost unchanged). Expensive: doubled. Free: uncharged,
    charged, and combo-ammo costs are all 0 (the combo missile cost still
    applies -- open-prime-rando requires it to be at least 1).

    Doesn't affect logic: ammo *capacity* requirements (how many
    expansions are needed to progress) are unchanged by this option, only
    how fast that ammo is spent in combat."""

    display_name = "Beam Ammo Costs"
    option_vanilla = 0
    option_cheap = 1
    option_expensive = 2
    option_free = 3
    default = 0


class AnnihilatorAmmoSource(Choice):
    """Which ammo pool(s) the Annihilator Beam draws from per shot
    (open-prime-rando's per-beam ``BeamConfiguration.ammo_a``/``ammo_b``
    resource remapping).

    Both (vanilla, default): costs Dark Ammo and Light Ammo simultaneously,
    same as every other Prime 2 randomizer/vanilla. Dark Only / Light
    Only: the Annihilator Beam instead costs only that one ammo type,
    effectively free with respect to the other.

    Doesn't affect logic: the Annihilator Beam item itself is still a
    simple boolean requirement in the logic database (it doesn't model
    per-shot ammo consumption), so this is purely a combat-feel/difficulty
    tweak."""

    display_name = "Annihilator Beam Ammo Source"
    option_both = 0
    option_dark_only = 1
    option_light_only = 2
    default = 0


class DoubleDamageMultiplier(Range):
    """Damage multiplier (in percent) granted by the Double Damage item
    (open-prime-rando's "Massive Damage" custom item -- see
    ``custom_items.massive_damage_config.damage_increase_multiplier``).

    Default 200 (2.0x, i.e. actual double damage). Note open-prime-rando's
    own internal default for this field is 1.0 (100%, a no-op) -- this
    world always sets it explicitly so the item does what its name says
    unless deliberately changed.

    Double Damage isn't in the default item pool (`default_pool_count=0`
    in ``items.py``) so this only matters if a copy reaches you some other
    way (e.g. `start_inventory`)."""

    display_name = "Double Damage Multiplier"
    range_start = 100
    range_end = 500
    default = 200


class DefenseUpDamageReduction(Range):
    """Percentage of incoming damage permanently negated by open-prime-
    rando's "Defense Up" custom item (``custom_items.defense_up_config.
    damage_reduction_multiplier``), on top of (and independent of) the
    Dark Aether/Dark Suit damage math `dark_aether_damage`/
    `dark_suit_damage` already model.

    Default 0 (vanilla -- no effect). Defense Up reuses the Varia Suit
    inventory slot as its internal counter, and this world always keeps
    Varia Suit's capacity locked at exactly 1 (see
    ``client/receive_items.py``), so this is a single flat value applied
    from the start of the game -- not a stacking pickup. Not modeled in
    logic (a non-zero value can only make survival easier than logic
    assumes, never harder)."""

    display_name = "Defense Up Damage Reduction"
    range_start = 0
    range_end = 90
    default = 0


@dataclass
class MetroidPrime2Options(PerGameCommonOptions):
    start_inventory_from_pool: StartInventoryPool

    goal: Goal
    sky_temple_keys: SkyTempleKeys
    sky_temple_keys_locations: SkyTempleKeysLocations
    sky_temple_keys_required: SkyTempleKeysRequired
    sky_temple_key_hints: SkyTempleKeyHints
    translator_lore_hints: TranslatorLoreHints
    translator_lore_rando: TranslatorLoreRando
    progressive_suit: ProgressiveSuit
    progressive_grapple: ProgressiveGrapple
    missile_expansions_unlock_launcher: MissileExpansionsUnlockLauncher
    power_bomb_expansions_unlock_power_bombs: PowerBombExpansionsUnlockPowerBombs
    split_beam_ammo: SplitBeamAmmo

    trick_level: TrickLevel
    trick_airunderwater: TrickAirUnderwater
    trick_bsj: TrickBSJ
    trick_bombjump: TrickBombJump
    trick_bomblessslot: TrickBomblessSlot
    trick_boostjump: TrickBoostJump
    trick_combat: TrickCombat
    trick_dash: TrickDash
    trick_edash: TrickEDash
    trick_enemyhop: TrickEnemyHop
    trick_instantmorph: TrickInstantMorph
    trick_invisibleobjects: TrickInvisibleObjects
    trick_knowledge: TrickKnowledge
    trick_movement: TrickMovement
    trick_nosuits: TrickNoSuits
    trick_oob: TrickOoB
    trick_rolljump: TrickRollJump
    trick_sanosj: TrickSAnoSJ
    trick_scanpost: TrickScanPost
    trick_screwattacktunnels: TrickScrewAttackTunnels
    trick_seekerlesslocks: TrickSeekerlessLocks
    trick_slopejump: TrickSlopeJump
    trick_standableterrain: TrickStandableTerrain
    trick_terminalfall: TrickTerminalFall
    trick_underwaterdash: TrickUnderwaterDash
    trick_wallboost: TrickWallBoost

    damage_strictness: DamageStrictness
    energy_per_tank: EnergyPerTank
    max_energy_tanks: MaxEnergyTanks
    dark_aether_damage: DarkAetherDamage
    dark_suit_damage: DarkSuitDamage
    dangerous_energy_tanks: DangerousEnergyTanks

    beam_ammo_costs: BeamAmmoCosts
    annihilator_ammo_source: AnnihilatorAmmoSource
    double_damage_multiplier: DoubleDamageMultiplier
    defense_up_damage_reduction: DefenseUpDamageReduction

    door_lock_rando: DoorLockRando
    normal_save_station_doors: NormalSaveStationDoors
    elevator_rando: ElevatorRando
    portal_rando: PortalRando
    translator_gate_rando: TranslatorGateRando
    starting_room: StartingRoom
    starting_room_light_world_only: StartingRoomLightWorldOnly

    warp_to_start: WarpToStart
    pre_scan_elevators: PreScanElevators
    move_while_scanning: MoveWhileScanning
    spring_ball: SpringBall
    spring_ball_button: SpringBallButton

    display_nonlocal_items: DisplayNonLocalItems
    map_visibility: MapVisibility
    item_map_dots: ItemMapDots
    unvisited_room_names: UnvisitedRoomNames

    death_link: DeathLink

    # Folded into map_visibility (PLAN.md section M). Shipped in 1.0.0, so
    # this shim makes an old YAML's `reveal_map: true` fail with a message
    # naming its replacement instead of being silently dropped, while
    # `reveal_map: false` -- what the 1.0.0 example config shipped, and
    # equivalent to map_visibility's `vanilla` default -- still generates.
    reveal_map: RevealMapRemoved


OPTION_GROUPS: list[OptionGroup] = [
    OptionGroup(
        "Goal",
        [
            Goal,
            SkyTempleKeys,
            SkyTempleKeysLocations,
            SkyTempleKeysRequired,
            SkyTempleKeyHints,
            TranslatorLoreHints,
            TranslatorLoreRando,
        ],
    ),
    OptionGroup(
        "Item Pool",
        [
            ProgressiveSuit,
            ProgressiveGrapple,
            MissileExpansionsUnlockLauncher,
            PowerBombExpansionsUnlockPowerBombs,
            SplitBeamAmmo,
        ],
    ),
    OptionGroup(
        "Logic",
        [
            TrickLevel,
            DamageStrictness,
            EnergyPerTank,
            MaxEnergyTanks,
            DarkAetherDamage,
            DarkSuitDamage,
            DangerousEnergyTanks,
        ],
    ),
    OptionGroup(
        "Combat",
        [
            BeamAmmoCosts,
            AnnihilatorAmmoSource,
            DoubleDamageMultiplier,
            DefenseUpDamageReduction,
        ],
    ),
    OptionGroup(
        "Entrances",
        [
            DoorLockRando,
            NormalSaveStationDoors,
            ElevatorRando,
            PortalRando,
            TranslatorGateRando,
            StartingRoom,
            StartingRoomLightWorldOnly,
        ],
    ),
    OptionGroup(
        "Tricks",
        [
            TrickAirUnderwater,
            TrickBSJ,
            TrickBombJump,
            TrickBomblessSlot,
            TrickBoostJump,
            TrickCombat,
            TrickDash,
            TrickEDash,
            TrickEnemyHop,
            TrickInstantMorph,
            TrickInvisibleObjects,
            TrickKnowledge,
            TrickMovement,
            TrickNoSuits,
            TrickOoB,
            TrickRollJump,
            TrickSAnoSJ,
            TrickScanPost,
            TrickScrewAttackTunnels,
            TrickSeekerlessLocks,
            TrickSlopeJump,
            TrickStandableTerrain,
            TrickTerminalFall,
            TrickUnderwaterDash,
            TrickWallBoost,
        ],
        start_collapsed=True,
    ),
    OptionGroup(
        "Quality of Life",
        [WarpToStart, PreScanElevators, MoveWhileScanning, SpringBall, SpringBallButton],
    ),
    OptionGroup(
        "Cosmetic",
        [DisplayNonLocalItems, MapVisibility, ItemMapDots, UnvisitedRoomNames],
    ),
]


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------

# Trick difficulty levels: 0 disabled .. 5 ludicrous, matching TrickLevel
# and every per-trick Choice's option_* values shifted by 1 (option_disabled
# = 1 there because 0 is reserved for "use_global").
_MAX_TRICK_LEVEL = 5


def trick_levels_from_options(options: MetroidPrime2Options) -> dict[str, int]:
    """Map each DB trick short_name to its effective 0..5 difficulty level.

    For each trick, the per-trick option (``trick_<short_name>``) wins
    when set to anything but "use_global" (0); otherwise the global
    ``trick_level`` option applies.
    """
    global_level = options.trick_level.value
    levels: dict[str, int] = {}
    for short_name, field_name in TRICK_OPTION_NAMES.items():
        per_trick = getattr(options, field_name).value
        levels[short_name] = global_level if per_trick == 0 else per_trick - 1
    return levels


# damage_strictness option value -> randovania multiplier.
_DAMAGE_STRICTNESS_MULTIPLIERS = {
    DamageStrictness.option_strict: 1.0,
    DamageStrictness.option_medium: 1.5,
    DamageStrictness.option_lenient: 2.0,
}


def damage_strictness_multiplier(options: MetroidPrime2Options) -> float:
    return _DAMAGE_STRICTNESS_MULTIPLIERS[options.damage_strictness.value]


# DarkAetherDamage/DarkSuitDamage are stored in tenths of a point per second
# (see their docstrings); every call site (logic and the ISO patcher alike)
# needs real damage/second units, so they share this one conversion instead
# of each re-deriving the /10.0 scale factor.
def dark_damage_per_second(option_value_tenths: int) -> float:
    return option_value_tenths / 10.0
